[package]
name = "csqrl/packager"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "https://github.com/csqrl/packager"

[dependencies]
DumpParser = "csqrl/dump-parser@0.1.2"
